
name: 'Concat a message on pull-request body'
description: 'A github action to concat a message to pull request original body'
author: 'Fabiano Chiaretto Fernandes'
branding:
  icon: 'edit'
  color: 'purple'
runs:
  using: 'node15'
  main: 'dist/index.js'
inputs:
  github-token:
    description: 'The GITHUB_TOKEN secret'
    required: true
  message:
    description: 'Message to concatenate'
    required: true
  replace-last-message:
    description: 'Replace the last concatenated message'
    required: false
  pr-number:
    description: 'Force PR Number'
    required: false