name: Edit pull-request body
on: [pull_request]

uses: chiaretto/github-action-concat-pr-body@v1
with:
  github-token: "${{ secrets.GITHUB_TOKEN }}"
  message: "This pull request generated the following artifacts."