#name: Update pull-request body
#on: [pull_request]
#
#jobs:
#  update-pr:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Pull Request Number
#        id: pull-request-number
#        run: echo "::set-output name=pull-request-number::$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")"
#
#      - uses: actions/checkout@v2.3.4
#      - name: Create binary from branch
#        run: |
#          touch text.txt
#
#      - name: Upload binary
#        uses: actions/upload-artifact@v2
#        with:
#          name: rit-linux
#          path: text.txt
#
#      - name: Update PR Body
#        uses: chiaretto/github-action-concat-pr-body@branch1
#        with:
#          github-token: "${{ secrets.GITHUB_TOKEN }}"
#          message: "
#          ### This pull request generated the following artifacts.
#
#To test the health and quality of this implementation, download the respective binary
#for your operating system, unzip and directly run the binary like the examples below.
#
#- **Windows**\r
#Download the file: **[rit-windows.zip](url)**\r
#Unzip to some folder like `C:\\home\\user\\downloads\\pr${{ steps.pull-request-number.outputs.pull-request-number }}`\r
#Access the folder: `cd C:\\home\\user\\downloads\\pr${{ steps.pull-request-number.outputs.pull-request-number }}`\r
#Directly call the binary: `.\\rit.exe --version` or `.\\rit.exe name of formula`\r
#\r\r
#- **Linux**\r
#Download the file: **[rit-linux.zip](url)**\r
#Unzip to some folder like /home/user/downloads/pr${{ steps.pull-request-number.outputs.pull-request-number }}`\r
#Access the folder: cd /home/user/downloads/pr${{ steps.pull-request-number.outputs.pull-request-number }}`\r
#Directly call the binary: ./rit --version` or `./rit.exe name of formula`\r
#\r\r
#- **MacOS**\r
#Download the file: **[rit-macos.zip](url)**\r
#Unzip to some folder like: `/home/user/downloads/pr${{ steps.pull-request-number.outputs.pull-request-number }}`\r
#Access the folder: `cd /home/user/downloads/pr${{ steps.pull-request-number.outputs.pull-request-number }}`\r
#Directly call the binary: `./rit --version` or `./rit.exe name of formula`\r
#          "
#          replace-last-message: true