name: Update pull-request body
on: [pull_request]

jobs:
  update-pr-body:
    runs-on: ubuntu-latest
    steps:
      - name: Update PR Body
        uses: chiaretto/github-action-concat-pr-body@master
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          message: "### This pull request was automatically edited"
          replace-last-message: true