name: Update pull-request body
on: [pull_request]

jobs:
  update-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Request Number
        run: jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH"

      - name: Update PR Body
        uses: chiaretto/github-action-concat-pr-body@branch1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          message: "
          ### This pull request generated the following artifacts.

To test the health and quality of this implementation, download the respective binary
for your operating system, unzip and directly run the binary like the examples below.

- **Windows**
Download the file: **[rit-windows.zip](url)**
Unzip to some folder like `C:\home\user\downloads\pr367`
Access the folder: `cd C:\home\user\downloads\pr367`
Directly call the binary: `./rit.exe --version` or `./rit.exe name of formula`

- **Linux**
Download the file: **[rit-linux.zip](url)**
Unzip to some folder like /home/user/downloads/pr367`
Access the folder: cd /home/user/downloads/pr367`
Directly call the binary: ./rit --version` or `./rit.exe name of formula`

- **MacOS**
Download the file: **[rit-macos.zip](url)**
Unzip to some folder like: `/home/user/downloads/pr367`
Access the folder: `cd /home/user/downloads/pr367`
Directly call the binary: `./rit --version` or `./rit.exe name of formula`
          "
          replace-last-message: true