name: Update pull-request body
on: [pull_request]

jobs:
  update-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Update PR Body
        uses: chiaretto/github-action-concat-pr-body@branch1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          message: "This pull request generated the following artifacts."
          replace-last-message: true