name: List Artifacts And Edit Pull Request
on:
  workflow_run:
    workflows: ["Generate Artifacts"]
    types: [completed]

jobs:
  list-artifacts-edit-pr-body:
    runs-on: ubuntu-latest
    steps:
      - name: List artifacts
        id: list-artifacts
        uses: chiaretto/github-action-list-artifacts-pr@master
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Print variables
        run: |
          echo artifact-name: ${{ steps.list-artifacts.outputs.artifact-name }}

      - name: Update PR Body
        uses: chiaretto/github-action-concat-pr-body@branch1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          message: "
### This pull request generated the following artifacts.

Download artifact url: ${{ steps.list-artifacts.outputs.artifact-name }}
"
          replace-last-message: true